# Generated by Django 5.2.7 on 2025-10-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0002_type_employe_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
