# Generated by Django 5.2.7 on 2025-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0003_alter_type_options_alter_type_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='employe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AddField(
            model_name='employe',
            name='categories',
            field=models.ManyToManyField(to='daw.category', verbose_name='Categorias'),
        ),
    ]
