# Generated by Django 5.2.7 on 2025-10-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0005_chavez_josue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavez',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='ecuador'),
        ),
        migrations.CreateModel(
            name='cristopher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(verbose_name='Coop. La Auroroa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='14-10-2025')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='15-10-2025')),
                ('nombre', models.CharField(max_length=150, verbose_name='cristopher')),
                ('email', models.EmailField(max_length=150, verbose_name='cristopherchavez231@gmail.com')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.chavez', verbose_name='ecuador')),
            ],
        ),
        migrations.DeleteModel(
            name='JOSUE',
        ),
    ]
