# Generated by Django 5.2.7 on 2025-10-14 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0006_alter_chavez_nombre_cristopher_delete_josue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavez',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='ECUADOR'),
        ),
        migrations.CreateModel(
            name='JOSUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='JOSUE')),
                ('email', models.EmailField(max_length=150, verbose_name='josuecha102@gmail.com')),
                ('direccion', models.TextField(verbose_name='Calle libertadores')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='14/10/2025')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='14/10/2025')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.chavez', verbose_name='ECUADOR')),
            ],
        ),
        migrations.DeleteModel(
            name='cristopher',
        ),
    ]
