# Generated by Django 5.2.7 on 2025-10-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0007_alter_chavez_nombre_josue_delete_cristopher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavez',
            options={'ordering': ['id'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='josue',
            options={'ordering': ['id'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelTable(
            name='chavez',
            table='pais',
        ),
        migrations.AlterModelTable(
            name='josue',
            table='estudiante',
        ),
    ]
