# Generated by Django 5.2.7 on 2025-10-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0008_alter_chavez_options_alter_josue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavez',
            options={},
        ),
        migrations.AlterModelOptions(
            name='josue',
            options={},
        ),
        migrations.AlterModelTable(
            name='chavez',
            table=None,
        ),
        migrations.AlterModelTable(
            name='josue',
            table=None,
        ),
    ]
