# Generated by Django 5.2.7 on 2025-10-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0009_alter_chavez_options_alter_josue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Aseguradora')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'db_table': 'aseguradora',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('identificacion', models.CharField(max_length=13, verbose_name='RUC o Identificación')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo Electrónico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Foto')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae', verbose_name='Currículum Vitae')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo de Seguro')),
            ],
            options={
                'verbose_name': 'Tipo de Seguro',
                'verbose_name_plural': 'Tipos de Seguro',
                'db_table': 'tipo_seguro',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='employe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='josue',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='type',
        ),
        migrations.CreateModel(
            name='PolizaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de Póliza')),
                ('fecha', models.DateField(verbose_name='Fecha de Registro')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('valor_seguro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Seguro')),
                ('valor_prima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Prima')),
                ('valor_adicional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Adicional')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.aseguradora', verbose_name='Aseguradora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.cliente', verbose_name='Cliente')),
                ('tipo_seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.tiposeguro', verbose_name='Tipo de Seguro')),
            ],
            options={
                'verbose_name': 'Póliza de Seguro',
                'verbose_name_plural': 'Pólizas de Seguro',
                'db_table': 'poliza_seguro',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CHAVEZ',
        ),
        migrations.DeleteModel(
            name='JOSUE',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
