# Generated by Django 5.2.7 on 2025-10-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0010_aseguradora_cliente_tiposeguro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polizaseguro',
            options={'ordering': ['id'], 'verbose_name': 'Poliza de Seguro', 'verbose_name_plural': 'Polizas de Seguro'},
        ),
    ]
