# Generated by Django 5.2.7 on 2025-10-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0011_alter_polizaseguro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polizaseguro',
            options={'ordering': ['id'], 'verbose_name': 'Poliza_de_Seguro', 'verbose_name_plural': 'Polizas_de_Seguro'},
        ),
        migrations.AlterModelOptions(
            name='tiposeguro',
            options={'ordering': ['id'], 'verbose_name': 'Tipo_de_Seguro', 'verbose_name_plural': 'Tipos_de_Seguro'},
        ),
        migrations.AlterField(
            model_name='aseguradora',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre_de_Aseguradora'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha_de_Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=13, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='fecha',
            field=models.DateField(verbose_name='Fecha_de_Registro'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha_de_Fin'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha_de_Inicio'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='numero_poliza',
            field=models.CharField(max_length=50, verbose_name='Número_de_Poliza'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='tipo_seguro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daw.tiposeguro', verbose_name='Tipo_de_Seguro'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='valor_adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor_Adicional'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='valor_prima',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor_Prima'),
        ),
        migrations.AlterField(
            model_name='polizaseguro',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor_del_Seguro'),
        ),
        migrations.AlterField(
            model_name='tiposeguro',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Tipo_de_Seguro'),
        ),
    ]
